apiVersion: v1
kind: Pod
metadata:
  generateName: besteffort-
spec:
  containers:
  - name: besteffort
    image: centos:7
    command:
      - sleep
      - infinity
    resources:
      limits:
#        memory: "2Gi"
#        cpu: "250m"
#      requests:
#        memory: "2Gi"
#        cpu: "250m"
#
#
#
#
#        apiVersion: v1
#        kind: Pod
#        metadata:
#          generateName: Burstable
#          spec:
#            containers:
#              - name: burstable
#                  image: centos:7
#                      command:
#                            - sleep
#                                  - infinity
#                                      resources:
#                                            requests:
#                                                    memory: "2Gi"
#                                                            cpu: "250m"
#
