apiVersion: v1
kind: Pod
metadata:
  generateName: guaranteed-
spec:
  containers:
  - name: guaranteed
    image: centos:7
    command:
      - sleep
      - infinity
    resources:
      limits:
        memory: "2Gi"
        cpu: "250m"
      requests:
        memory: "2Gi"
        cpu: "250m"
